version: "3.2"
services:

  full_2_3:
    image: selenium_chrome_headless_ruby:2.3.7
    build:
      context: .
      cache_from:
        - ruby:2.3.7
        - selenium_chrome_headless_ruby:2.3.7
        - nyulibraries/selenium_chrome_headless_ruby:2.3.7
        - nyulibraries/selenium_chrome_headless_ruby:2.3.7-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_3
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: "2.42"

  slim_2_3:
    image: selenium_chrome_headless_ruby:2.3.7-slim
    build:
      context: .
      dockerfile: Dockerfile.slim
      cache_from:
        - ruby:2.3.7-slim
        - selenium_chrome_headless_ruby:2.3.7-slim
        - nyulibraries/selenium_chrome_headless_ruby:2.3.7-slim
        - nyulibraries/selenium_chrome_headless_ruby:2.3.7-slim-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_3
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: "2.42"

  full_2_4:
    image: selenium_chrome_headless_ruby:2.4.4
    build:
      context: .
      cache_from:
        - ruby:2.4.4
        - selenium_chrome_headless_ruby:2.4.4
        - nyulibraries/selenium_chrome_headless_ruby:2.4.4
        - nyulibraries/selenium_chrome_headless_ruby:2.4.4-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_4
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: "2.42"

  slim_2_4:
    image: selenium_chrome_headless_ruby:2.4.4-slim
    build:
      context: .
      dockerfile: Dockerfile.slim
      cache_from:
        - ruby:2.4.4-slim
        - selenium_chrome_headless_ruby:2.4.4-slim
        - nyulibraries/selenium_chrome_headless_ruby:2.4.4-slim
        - nyulibraries/selenium_chrome_headless_ruby:2.4.4-slim-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_4
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: "2.42"

  full_2_5:
    image: selenium_chrome_headless_ruby:2.5.1
    build:
      context: .
      cache_from:
        - ruby:2.5.1
        - selenium_chrome_headless_ruby:2.5.1
        - nyulibraries/selenium_chrome_headless_ruby:2.5.1
        - nyulibraries/selenium_chrome_headless_ruby:2.5.1-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_5
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: "2.42"

  slim_2_5:
    image: selenium_chrome_headless_ruby:2.5.1-slim
    build:
      context: .
      dockerfile: Dockerfile.slim
      cache_from:
        - ruby:2.5.1-slim
        - selenium_chrome_headless_ruby:2.5.1-slim
        - nyulibraries/selenium_chrome_headless_ruby:2.5.1-slim
        - nyulibraries/selenium_chrome_headless_ruby:2.5.1-slim-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_5
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: "2.42"
