version: "3.2"
services:

  full_2_3:
    image: selenium_chrome_headless_ruby:$RUBY_2_3
    build:
      context: .
      cache_from:
        - ruby:$RUBY_2_3
        - selenium_chrome_headless_ruby:$RUBY_2_3
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_3
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_3-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_3
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: $CHROMIUM_DRIVER_VERSION

  slim_2_3:
    image: selenium_chrome_headless_ruby:$RUBY_2_3-slim
    build:
      context: .
      dockerfile: Dockerfile.slim
      cache_from:
        - ruby:$RUBY_2_3-slim
        - selenium_chrome_headless_ruby:$RUBY_2_3-slim
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_3-slim
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_3-slim-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_3
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: $CHROMIUM_DRIVER_VERSION

  full_2_4:
    image: selenium_chrome_headless_ruby:$RUBY_2_4
    build:
      context: .
      cache_from:
        - ruby:$RUBY_2_4
        - selenium_chrome_headless_ruby:$RUBY_2_4
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_4
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_4-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_4
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: $CHROMIUM_DRIVER_VERSION

  slim_2_4:
    image: selenium_chrome_headless_ruby:$RUBY_2_4-slim
    build:
      context: .
      dockerfile: Dockerfile.slim
      cache_from:
        - ruby:$RUBY_2_4-slim
        - selenium_chrome_headless_ruby:$RUBY_2_4-slim
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_4-slim
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_4-slim-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_4
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: $CHROMIUM_DRIVER_VERSION

  full_2_5:
    image: selenium_chrome_headless_ruby:$RUBY_2_5
    build:
      context: .
      cache_from:
        - ruby:$RUBY_2_5
        - selenium_chrome_headless_ruby:$RUBY_2_5
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_5
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_5-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_5
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: $CHROMIUM_DRIVER_VERSION

  slim_2_5:
    image: selenium_chrome_headless_ruby:$RUBY_2_5-slim
    build:
      context: .
      dockerfile: Dockerfile.slim
      cache_from:
        - ruby:$RUBY_2_5-slim
        - selenium_chrome_headless_ruby:$RUBY_2_5-slim
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_5-slim
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_5-slim-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_5
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: $CHROMIUM_DRIVER_VERSION

  full_2_6:
    image: selenium_chrome_headless_ruby:$RUBY_2_6
    build:
      context: .
      cache_from:
        - ruby:$RUBY_2_6
        - selenium_chrome_headless_ruby:$RUBY_2_6
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_6
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_6-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_6
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: $CHROMIUM_DRIVER_VERSION

  slim_2_6:
    image: selenium_chrome_headless_ruby:$RUBY_2_6-slim
    build:
      context: .
      dockerfile: Dockerfile.slim
      cache_from:
        - ruby:$RUBY_2_6-slim
        - selenium_chrome_headless_ruby:$RUBY_2_6-slim
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_6-slim
        - quay.io/nyulibraries/selenium_chrome_headless_ruby:$RUBY_2_6-slim-$BRANCH_NO_SLASH
      args:
        RUBY_VERSION: $RUBY_2_6
        CHROME_VERSION: $CHROME_VERSION
        CHROMIUM_DRIVER_VERSION: $CHROMIUM_DRIVER_VERSION
