ARG RUBY_VERSION=2.5

FROM ruby:${RUBY_VERSION}-slim

# Install dependencies & Chrome
ENV CHROMIUM_DRIVER_VERSION 2.38
ENV BUILD_DEP gnupg zlib1g-dev liblzma-dev unzip nodejs
ENV OTHER_DEP wget xvfb libgconf2-4 libnss3
RUN apt-get update && apt-get -y --no-install-recommends install $BUILD_DEP $OTHER_DEP \
 && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -  \
 && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
 && apt-get update && apt-get -y --no-install-recommends install google-chrome-stable \
 && wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$CHROMIUM_DRIVER_VERSION/chromedriver_linux64.zip \
     && unzip /tmp/chromedriver.zip chromedriver -d /usr/bin/ \
     && rm /tmp/chromedriver.zip \
     && chmod ugo+rx /usr/bin/chromedriver \
 && apt-get --purge -y autoremove $BUILD_DEP \
 && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY docker-entrypoint.sh ./

ENTRYPOINT ["/docker-entrypoint.sh"]
