ARG RUBY_VERSION=2.6

FROM ruby:${RUBY_VERSION}-slim

ARG INSTALL_PATH=/app
RUN groupadd -g 2000 docker -r && \
  useradd -u 1000 -r --no-log-init -m -d "$INSTALL_PATH" -g docker docker

# Install dependencies & Chrome
ARG BUILD_PACKAGES="gnupg zlib1g-dev liblzma-dev unzip nodejs"
ARG RUN_PACKAGES="xvfb libgconf-2-4 libnss3 wget"
ARG CHROME_VERSION
ARG CHROMIUM_DRIVER_VERSION
SHELL ["/bin/bash", "-eo", "pipefail", "-c"]
RUN apt-get update && apt-get -y --no-install-recommends install $BUILD_PACKAGES $RUN_PACKAGES \
  && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -  \
  && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
  && apt-get update && apt-get -y --no-install-recommends install google-chrome-stable=$CHROME_VERSION \
  && wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/$CHROMIUM_DRIVER_VERSION/chromedriver_linux64.zip \
  && unzip /tmp/chromedriver.zip chromedriver -d /usr/bin/ \
  && rm /tmp/chromedriver.zip \
  && chmod ugo+rx /usr/bin/chromedriver \
  && apt-get --purge -y autoremove $BUILD_PACKAGES \
  && apt-get clean && rm -rf /var/lib/apt/lists/*

USER docker
WORKDIR $INSTALL_PATH
COPY script/docker-entrypoint.sh ./

ENTRYPOINT ["/app/docker-entrypoint.sh"]
