# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    docker:
      - image: quay.io/nyulibraries/circleci_docker:18.06.1-dc-1.23.2-0
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
        #      - run:
        #          name: Pull images
        #          command: |
        #            ./script/pull_dockers.sh
      - run:
          name: Build images
          command: |
            export BRANCH_NO_SLASH=${CIRCLE_BRANCH//\//_}
            docker-compose build
      - run:
          name: Authenticate docker
          command: |
            docker login -u "$QUAY_USERNAME" --password "$QUAY_PASSWORD" quay.io
      - run:
          name: Push images
          command: |
            env $(cat .env | xargs) script/push_dockers.sh
