# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
version: 2
jobs:
  build:
    docker:
      - image: nyulibraries/circleci_docker:18.06.1-ce-git
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Pull images
          command: |
            ./script/pull_dockers.sh
      - run:
          name: Build images
          command: |
            docker-compose build
      - run:
          name: Authenticate docker
          command: |
            docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - run:
          name: Push images
          command: |
            ./script/push_dockers.sh
